use std::path::PathBuf;
use cratty_core::{PaneId, WorkspaceId};
#[derive(Debug, Clone)]
pub enum Message {
    NewWorkspace,
    WorkspaceFolderPicked(Option<PathBuf>),
    CloseWorkspace(usize),
    SwitchWorkspace(usize),
    NewPane,
    ClosePane(PaneId),
    CloseFocusedPane,
    FocusPaneLeft,
    FocusPaneRight,
    MovePaneLeft,
    MovePaneRight,
    CyclePresetWidth,
    ToggleMaximizePane,
    GrowPane,
    ShrinkPane,
    ToggleSidebar,
    RenameWorkspace(WorkspaceId),
    RenameInput(String),
    RenameSubmit,
    SetWorkspaceColor(WorkspaceId, iced::Color),
    ShowWsMenu(usize),
    HideWsMenu,
    ToggleColorSubmenu,
    WindowResized(iced::Size),
    DragWindow,
    Minimize,
    Maximize,
    CloseWindow,
    ScrollTermUp,
    ScrollTermDown,
    CopyTerminal,
    PasteTerminal,
    EscapePressed,
    ToggleQuake,
    CodeAction(PaneId, iced::widget::text_editor::Action),
    SaveFocusedFile,
    OpenFilePicker,
    FilePickerInput(String),
    FilePickerMove(i32),
    FilePickerSelect(usize),
    FilePickerOpen,
    FilePickerClose,
    Tick,
}
