[package]
name = "cratty_app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cratty"
path = "src/main.rs"

[dependencies]
cratty_core = { workspace = true }
iced = { workspace = true }
iced_graphics = { workspace = true }
iced_core = { workspace = true }
alacritty_terminal = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
arboard = { workspace = true }
